<?php

declare(strict_types=1);

return [
    'engine' => env('RADIO_ENGINE', 'icecast'),
    'internal_token' => env('RADIO_INTERNAL_TOKEN'),
    'public_stream_url' => env('RADIO_PUBLIC_STREAM_URL'),
    'icecast_base_url' => env('ICECAST_BASE_URL', 'http://127.0.0.1:8000'),
    'icecast_mount' => env('ICECAST_MOUNT', '/arborisis.mp3'),
    'icecast_admin_user' => env('ICECAST_ADMIN_USER', 'admin'),
    'icecast_admin_password' => env('ICECAST_ADMIN_PASSWORD'),
    'icy_metaint' => env('RADIO_ICY_METAINT', 8192),
    'chunk_size' => env('RADIO_CHUNK_SIZE', 8192),
    'crossfade_enabled' => env('RADIO_CROSSFADE_ENABLED', false),
    'crossfade_seconds' => env('RADIO_CROSSFADE_SECONDS', 4),
    'fallback_sounds' => array_filter(explode(',', env('RADIO_FALLBACK_SOUNDS', ''))),
    'history_limit' => env('RADIO_HISTORY_LIMIT', 20),
    'playlist_shuffle' => env('RADIO_PLAYLIST_SHUFFLE', true),
    'temp_url_ttl_minutes' => env('RADIO_TEMP_URL_TTL', 60),
    'silence_file' => env('RADIO_SILENCE_FILE', null),
    'loop' => env('RADIO_LOOP', true),
    'gap_ms' => env('RADIO_GAP_MS', 500),
    'listener_ttl_seconds' => env('RADIO_LISTENER_TTL_SECONDS', 120),
    'dj' => [
        'enabled' => env('RADIO_DJ_ENABLED', true),
        'announcement_frequency' => env('RADIO_DJ_ANNOUNCEMENT_FREQUENCY', 3),
        'voice_provider' => env('RADIO_DJ_VOICE_PROVIDER', 'elevenlabs'),
        'voice_id' => env('RADIO_DJ_VOICE_ID'),
        'elevenlabs_voice_id' => env('ELEVENLABS_VOICE_ID'),
    ],
    'discord' => [
        'voice_channel_id' => env('DISCORD_RADIO_VOICE_CHANNEL_ID'),
        'auto_join' => env('DISCORD_RADIO_AUTO_JOIN', true),
    ],
    'audio_cache' => [
        'disk' => env('RADIO_AUDIO_CACHE_DISK', 'radio_cache'),
        'url_base' => env('RADIO_CACHE_URL_BASE', config('app.url')),
    ],
    'podcast' => [
        'enabled' => env('RADIO_PODCAST_ENABLED', false),
        'interval_tracks' => env('RADIO_PODCAST_INTERVAL_TRACKS', 15),
        'min_duration' => env('RADIO_PODCAST_MIN_DURATION', 600),
        'max_duration' => env('RADIO_PODCAST_MAX_DURATION', 1200),
        'min_sounds' => env('RADIO_PODCAST_MIN_SOUNDS', 4),
        'max_sounds' => env('RADIO_PODCAST_MAX_SOUNDS', 7),
        'voice_id' => env('RADIO_PODCAST_VOICE_ID') ?? env('RADIO_DJ_VOICE_ID'),
    ],
    'production' => [
        'enabled' => env('RADIO_AUDIO_PRODUCTION_ENABLED', true),
        'ai_enabled' => env('RADIO_AUDIO_PRODUCTION_AI_ENABLED', true),
        'ai_model' => env('RADIO_AUDIO_PRODUCTION_AI_MODEL', env('RADIO_HOST_AI_MODEL', 'anthropic/claude-opus-4.7')),
        'music_enabled' => env('RADIO_AUDIO_PRODUCTION_MUSIC_ENABLED', true),
        'sound_effects_enabled' => env('RADIO_AUDIO_PRODUCTION_FX_ENABLED', true),
        'max_music_seconds' => env('RADIO_AUDIO_PRODUCTION_MAX_MUSIC_SECONDS', 90),
        'music_volume' => env('RADIO_AUDIO_PRODUCTION_MUSIC_VOLUME', 0.12),
        'field_bed_volume' => env('RADIO_AUDIO_PRODUCTION_FIELD_BED_VOLUME', 0.16),
        'ident_volume' => env('RADIO_AUDIO_PRODUCTION_IDENT_VOLUME', 0.22),
        'ident_seconds' => env('RADIO_AUDIO_PRODUCTION_IDENT_SECONDS', 5),
    ],
    'host' => [
        'flash_enabled'       => env('RADIO_HOST_FLASH_ENABLED', false),
        'emission_enabled'    => env('RADIO_HOST_EMISSION_ENABLED', false),
        'flash_min_duration'  => 90,
        'flash_max_duration'  => 180,
        'emission_min_sounds' => 3,
        'emission_max_sounds' => 5,
        'host_voice_id'       => env('RADIO_HOST_VOICE_ID'),
        'ai_model'            => env('RADIO_HOST_AI_MODEL', 'anthropic/claude-opus-4.7'),
        'storage_disk'        => env('RADIO_HOST_STORAGE_DISK', 'r2'),

        // Phase 2 — Personnalités d'animateur IA-driven.
        'personalities_enabled' => env('RADIO_HOST_PERSONALITIES_ENABLED', false),
        'continuity_enabled'    => env('RADIO_HOST_CONTINUITY_ENABLED', false),
        'dj_ai_enabled'         => env('RADIO_HOST_DJ_AI_ENABLED', false),
        'dj_script_max_tokens'  => env('RADIO_HOST_DJ_SCRIPT_MAX_TOKENS', 320),
        'dj_script_temperature' => env('RADIO_HOST_DJ_SCRIPT_TEMPERATURE', 0.85),
        'dj_fingerprint_window' => env('RADIO_HOST_DJ_FINGERPRINT_WINDOW', 30),
        'dj_solo_streak_max'    => env('RADIO_HOST_DJ_SOLO_STREAK_MAX', 2),
    ],

    // Production presets per show_type (Phase 4).
    'presets' => [
        'podcast_intimate' => [
            'loudness_i'         => -16.0,
            'loudness_tp'        => -1.5,
            'loudness_lra'       => 14,
            'sidechain_ratio'    => 8,
            'sidechain_attack'   => 20,
            'sidechain_release'  => 700,
            'voice_highpass_hz'  => 70,
            'music_volume'       => 0.10,
            'field_bed_volume'   => 0.18,
            'ident_volume'       => 0.20,
            'max_music_seconds'  => 70,
            'music_coverage'     => 0.50,
        ],
        'flash_punchy' => [
            'loudness_i'         => -14.0,
            'loudness_tp'        => -1.0,
            'loudness_lra'       => 7,
            'sidechain_ratio'    => 12,
            'sidechain_attack'   => 12,
            'sidechain_release'  => 480,
            'voice_highpass_hz'  => 80,
            'music_volume'       => 0.18,
            'field_bed_volume'   => 0.10,
            'ident_volume'       => 0.28,
            'max_music_seconds'  => 60,
            'music_coverage'     => 0.90,
        ],
        'emission_cinematic' => [
            'loudness_i'         => -16.0,
            'loudness_tp'        => -1.5,
            'loudness_lra'       => 11,
            'sidechain_ratio'    => 10,
            'sidechain_attack'   => 25,
            'sidechain_release'  => 750,
            'voice_highpass_hz'  => 70,
            'music_volume'       => 0.12,
            'field_bed_volume'   => 0.16,
            'ident_volume'       => 0.22,
            'max_music_seconds'  => 90,
            'music_coverage'     => 0.60,
        ],
        'dj_brief' => [
            'loudness_i'         => -14.0,
            'loudness_tp'        => -1.2,
            'loudness_lra'       => 9,
            'sidechain_ratio'    => 8,
            'sidechain_attack'   => 10,
            'sidechain_release'  => 400,
            'voice_highpass_hz'  => 80,
            'music_volume'       => 0.08,
            'field_bed_volume'   => 0.14,
            'ident_volume'       => 0.20,
            'max_music_seconds'  => 30,
            'music_coverage'     => 1.00,
        ],
        'interlude' => [
            'loudness_i'         => -18.0,
            'loudness_tp'        => -2.0,
            'loudness_lra'       => 12,
            'sidechain_ratio'    => 6,
            'sidechain_attack'   => 30,
            'sidechain_release'  => 900,
            'voice_highpass_hz'  => 50,
            'music_volume'       => 0.16,
            'field_bed_volume'   => 0.20,
            'ident_volume'       => 0.12,
            'max_music_seconds'  => 120,
            'music_coverage'     => 0.40,
        ],
    ],

    // Monitoring & alerting (Phase 7 — provisionné en Phase 1 pour cohérence config).
    'monitoring' => [
        'enabled' => env('RADIO_MONITORING_ENABLED', false),
        'discord_webhook_url' => env('RADIO_MONITORING_DISCORD_WEBHOOK_URL'),
        'notification_debounce_minutes' => env('RADIO_MONITORING_NOTIFICATION_DEBOUNCE', 15),
    ],

    // Circuit breaker thresholds (Phase 7 — provisionné en Phase 1 pour cohérence config).
    'circuit_breaker' => [
        'elevenlabs' => [
            'failure_threshold' => env('RADIO_CB_ELEVENLABS_THRESHOLD', 5),
            'recovery_seconds'  => env('RADIO_CB_ELEVENLABS_RECOVERY', 120),
        ],
        'openrouter' => [
            'failure_threshold' => env('RADIO_CB_OPENROUTER_THRESHOLD', 5),
            'recovery_seconds'  => env('RADIO_CB_OPENROUTER_RECOVERY', 120),
        ],
    ],
];
